name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || contains(github.event.head_commit.message, '[e2e]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check if E2E tests exist
        id: check-e2e
        run: |
          if [ -d "ui-e2e" ] && [ -f "ui-e2e/playwright.config.ts" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Playwright browsers
        if: steps.check-e2e.outputs.exists == 'true'
        run: npx playwright install --with-deps

      - name: Build application
        if: steps.check-e2e.outputs.exists == 'true'
        run: npm run build

      - name: Run E2E tests
        if: steps.check-e2e.outputs.exists == 'true'
        run: npx nx e2e ui-e2e
        timeout-minutes: 10

      - name: Upload Playwright Report
        if: always() && steps.check-e2e.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui-e2e/playwright-report/
          retention-days: 30

      - name: Skip E2E tests
        if: steps.check-e2e.outputs.exists == 'false'
        run: echo "E2E tests not configured yet - skipping"

